power<- read.delim("household_power_consumption.txt", sep= ";")
power$Date<- as.Date(power$Date, "%d/%m/%Y")
power$Time<- strptime(power$Time, format="%H:%M:%S")
subpower<- subset(power, power$Date=="2007/02/01"| power$Date=="2007/02/02")
subpower[1:1440,"Time"] <- format(subpower[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subpower[1441:2880,"Time"] <- format(subpower[1441:2880,"Time"],"2007-02-02 %H:%M:%S")

png(filename = "plot3.png", width=480, height=480, units= "px")
plot(subpower$Time,as.numeric(subpower$Sub_metering_1),type="n",xlab="",ylab="Global Active Power (kilowatts)", main = "Global Active Power vs Time") 
with(subpower, lines(Time,as.numeric(Sub_metering_1)))
with(subpower, lines(Time,as.numeric(Sub_metering_2), col="red"))
with(subpower, lines(Time,as.numeric(Sub_metering_3), col= "blue"))
legend("topright", lty = c(1,1), lwd = c(1,1), col = c("black", "red", "blue"), legend=c("Sub metering 1","Sub metering 2","Sub metering 3"), pt.cex = 1)
dev.off()
